project_name: filebrowser

env:
  - GO111MODULE=on

build:
  env:
    - CGO_ENABLED=0
  ldflags:
    - -s -w -X github.com/uetuluk/filebrowser/v2/version.Version={{ .Version }} -X github.com/uetuluk/filebrowser/v2/version.CommitSHA={{ .ShortCommit }}
  main: main.go
  binary: filebrowser
  goos:
    - linux
    - windows
  goarch:
    - amd64
  ignore:
    - goos: darwin
      goarch: 386
    - goos: freebsd
      goarch: arm

archives:
  -
    name_template: "{{.Os}}-{{.Arch}}{{if .Arm}}v{{.Arm}}{{end}}-{{ .ProjectName }}"
    format: tar.gz
    format_overrides:
      - goos: windows
        format: zip

dockers:
  -
    dockerfile: Dockerfile
    use: buildx
    build_flag_templates:
      - "--pull"
      - "--label=org.opencontainers.image.created={{.Date}}"
      - "--label=org.opencontainers.image.name={{.ProjectName}}"
      - "--label=org.opencontainers.image.revision={{.FullCommit}}"
      - "--label=org.opencontainers.image.version={{.Version}}"
      - "--label=org.opencontainers.image.source={{.GitURL}}"
      - "--platform=linux/amd64"
    goos: linux
    goarch: amd64
    image_templates:
      - "uetuluk/filebrowser:{{ .Tag }}-amd64"
      - "uetuluk/filebrowser:v{{ .Major }}-amd64"
    extra_files:
      - docker_config.json
## s6 based docker images
  -
    dockerfile: Dockerfile.s6
    use: buildx
    build_flag_templates:
      - "--pull"
      - "--label=org.opencontainers.image.created={{.Date}}"
      - "--label=org.opencontainers.image.name={{.ProjectName}}"
      - "--label=org.opencontainers.image.revision={{.FullCommit}}"
      - "--label=org.opencontainers.image.version={{.Version}}"
      - "--label=org.opencontainers.image.source={{.GitURL}}"
      - "--platform=linux/amd64"
    goos: linux
    goarch: amd64
    image_templates:
      - "uetuluk/filebrowser:{{ .Tag }}-amd64-s6"
      - "uetuluk/filebrowser:v{{ .Major }}-amd64-s6"
    extra_files:
      - docker/root
docker_manifests:
  - name_template: "uetuluk/filebrowser:latest"
    image_templates:
      - "uetuluk/filebrowser:{{ .Tag }}-amd64"
  - name_template: "uetuluk/filebrowser:{{ .Tag }}"
    image_templates:
      - "uetuluk/filebrowser:{{ .Tag }}-amd64"
  - name_template: "uetuluk/filebrowser:v{{ .Major }}"
    image_templates:
      - "uetuluk/filebrowser:v{{ .Major }}-amd64"
## s6 image manifests
  - name_template: "filebrowser/filebrowser:s6"
    image_templates:
      - "uetuluk/filebrowser:{{ .Tag }}-amd64-s6"
  - name_template: "filebrowser/filebrowser:{{ .Tag }}-s6"
    image_templates:
      - "uetuluk/filebrowser:{{ .Tag }}-amd64-s6"
  - name_template: "filebrowser/filebrowser:v{{ .Major }}-s6"
    image_templates:
      - "uetuluk/filebrowser:v{{ .Major }}-amd64-s6"
