name: Sync Fork

on:
  schedule:
    - cron: '0 0 */1 * *' # every 7 days
  workflow_dispatch: # on button click

jobs:
  sync:

    runs-on: ubuntu-latest

    steps:
      - uses: tgymnich/fork-sync@v1.4
        with:
          owner: filebrowser
          base: master
          head: master
